### ISSUE TITLE
Usable for SVG?

### ISSUE THREAD

**Issue by PhilterPaper** [mgreter/OCBNET-CSS3#2]
Hi Marcel,

I am looking for already-written Perl modules to process SVG files. In case you're not familiar with Scalable Vector Graphics, it is XML-format with CSS to set properties. I already have found a module to parse the SVG itself, and am hoping to find a module to process CSS (.css files read in, `<style>` sections, inline `style="CSS stuff"`). If I were to use OCBNET::CSS3, how easy is it to build the CSS "DOM", and what information do I need to feed your library to retrieve all the properties pertaining to this element? I can have the element (tag), any id=, any class=, the parent chain, siblings, etc. I think it may be a bit simpler for SVG than for HTML. I'm trying to avoid writing all this stuff myself if someone has already got it working! Thanks much for any feedback you can give, or suggestions.

Phil

**Comment by mgreter** [comment]
Hey @PhilterPaper, unfortunately I don't think my module will give you all the features you need, according to your use case description. IMO what you're looking for is something one layer above OCBNET::CSS3, since you seem to want to match an actual SVG/HTML DOM against the parsed CSS. This is definitely not implemented by this module. This module merely provides the parsing of the CSS and some core functions to interact with it (and even quite sure lacks some use cases to "really" parse all valid css things).  On the other hand I don't know any other perl module to parse CSS into something usable, so it might be a start for what you want to achieve. I'm quite familiar what SVG can do, so I believe creating something to parse SVG and CSS to convert it into a PDF compatible format seems like a pretty big task!

Btw. I basically wrote this module to support https://github.com/mgreter/OCBNET-WebSprite, which only needs to know about a few properties (e.g. margin, padding, width, height etc). To support CSS/DOM inheritance I actually introduced a concept with comments (`css-ref/css-id`) so I can define the inheritance in the CSS files directly. Just for the sake of it I also added a few other parsers for e.g. font. The above reference code might help you if you really want to proceed to try to write your own SVG/CSS interpreter. 

But it is IMO a long way to go to match it against an "external" DOM. Sounds pretty much like writing the core of a Browser to match a DOM against CSS, which is probably really not an easy task! Maybe you're best of to just rasterize the SVG images via e.g. "rsvg-convert".

Best regards
Marcel

**Comment by PhilterPaper** [comment]
It's plenty easy to rasterize SVG and turn it into some other, bitmapped image form, but the whole idea here is to preserve the vector graphics aspect of it when I generate the equivalent PDF vector graphics. This is for the PDF::Builder project -- I want to support SVG graphics _as vector graphics in the resulting PDF_. 

I was hoping this library would be a general purpose CSS handler, handling all the selectors to assign the right properties to any given SVG element (given its tag, id, classes, and hierarchy), but it sounds like you're saying it has a long ways to go to do that. For the time being, I think I'll just handle the style= attribute (easy to parse) and save more advanced CSS for some time later. Maybe this layer above OCBNET::CSS3 would make a good module project for someone? It could be applied to HTML and XML, too.

By the way, do you know how to set up a CPAN package to list _optional_ packages in someone else's "reverse dependencies" area? For example, since few people would use SVG images, I wouldn't want to make installing OCBNET::CSS3 mandatory. I have some other "optional" packages that require certain lib___.a libraries, so I have to have PDF::Builder users manually install them if they want to use that functionality (TIFF images, PNG images, SVG images). Just as a courtesy, to show those packages are being used by someone (and to advertise my project), it would be nice to have PDF::Builder show up in their Reverse Dependencies list (without actually requiring that they be installed).
